export const skillMapping = {
	"agile methodologies": ['agile', 'agile methodology', 'agile software development'],
	"api design": ['api applications', 'api development'],
	"api rest": ['rest'],
	"azure": ['azure devops', 'azure services'],
	"cloud": ['cloud services', 'cloud technologies'],
	"data manipulation": ['data transformation'],
	"documentation": ['technical documentation'],
	"front-end development": ['frontend development'],
	"google cloud": ['google cloud platform'],
	"infrastructure as code": ['infrastructure-as-code'],
	"javascript": ['java script'],
	"non-relational databases": ['no-sql databases'],
	"requirements analysis": ['requirements gathering'],
	"security": ['security and compliance', 'security guidelines'],
	"stakeholder management": ['stakeholder communication'],
	"tailwind": ['tailwindcss'],
	"team management": ['team leadership'],
}
